MSR = 1
MAR = 2
MDR = 3
MC = 4
IR = 5
DST = 6
SRC = 7
A = 8
B = 9
C = 10
D = 11
DI = 12
SI = 13
SP = 14
BP = 15
CS = 16
DS = 17
SS = 18
ES = 19
VEC=20
T1=21
T2=22
T3=23

# 0-4位SC控制寄存器读(1-19需要5位)
MSR_OUT = MSR
MAR_OUT = MAR
MDR_OUT = MDR
MC_OUT = MC
IR_OUT = IR
DST_OUT = DST
SRC_OUT = SRC
A_OUT = A
B_OUT = B
C_OUT = C
D_OUT = D
DI_OUT = DI
SI_OUT = SI
SP_OUT = SP
BP_OUT = BP
CS_OUT = CS
DS_OUT = DS
SS_OUT = SS
ES_OUT = ES
VEC_OUT=VEC
T1_OUT=T1
T2_OUT=T2
T3_OUT=T3

#5-9位DC控制寄存器写
_DST_SHIFT = 5

MSR_IN = MSR << _DST_SHIFT
MAR_IN = MAR << _DST_SHIFT
MDR_IN = MDR << _DST_SHIFT
MC_IN = MC << _DST_SHIFT
IR_IN = IR << _DST_SHIFT
DST_IN = DST << _DST_SHIFT
SRC_IN = SRC << _DST_SHIFT
A_IN = A << _DST_SHIFT
B_IN = B << _DST_SHIFT
C_IN = C << _DST_SHIFT
D_IN = D << _DST_SHIFT
DI_IN = DI << _DST_SHIFT
SI_IN = SI << _DST_SHIFT
SP_IN = SP << _DST_SHIFT
BP_IN = BP << _DST_SHIFT
CS_IN = CS << _DST_SHIFT
DS_IN = CS << _DST_SHIFT
SS_IN = SS << _DST_SHIFT
ES_IN = ES << _DST_SHIFT
VEC_IN=VEC << _DST_SHIFT
T1_IN=T1 << _DST_SHIFT
T2_IN=T2 << _DST_SHIFT
T3_IN=T3 << _DST_SHIFT

DST_W = 1<<10
DST_R = 1<<11
SRC_W = 1<<12
SRC_R = 1<<13

PC_W = 1<<14
PC_CS = 1<<15
PC_EN = 1<<16

PC_INC = PC_W | PC_CS | PC_EN
PC_OUT = PC_CS 
PC_IN = PC_CS|PC_W

#op 7个状态需要3位
_OP_SHIFT = 17

ALU_OP_ADD = 0<<_OP_SHIFT
ALU_OP_SUB = 1<<_OP_SHIFT
ALU_OP_INC = 2<<_OP_SHIFT
ALU_OP_DEC = 3<<_OP_SHIFT
ALU_OP_XOR = 4<<_OP_SHIFT
ALU_OP_OR = 5<<_OP_SHIFT
ALU_OP_AND = 6<<_OP_SHIFT
ALU_OP_NOT = 7<<_OP_SHIFT

ALU_OUT = 1<<20
ALU_PSW = 1<<21
ALU_INT_W = 1<<22
ALU_INT = 1<<23

#开中断
ALU_STI = ALU_INT_W
#关中断
ALU_CLI = ALU_INT_W | ALU_INT

CYC = 1<<30
HLT = 1<<31

